### ISSUE TITLE
Clarify definition of <level> text in MusicXML

### ISSUE THREAD

**Issue by school510587** [w3c/musicxml#146]
The level tag seems to be used to specify editorial information for its parent element.
According to common.mod, it is not an empty element. However, there is no description about what the text of a level tag means.
Could you give some more description for <level> text? Thanks!

**Comment by mdgood** [comment]
@school510587 Thanks for raising this issue. This was a generalization of the integer level field in MuseData. In MusicXML it is used to identify and describe different types of editorial information. There is an example in Listing 19 of my paper on [Using MusicXML 2.0 for Editorial Applications](https://michaelgood.info/publications/music/using-musicxml-2-0-for-music-editorial-applications/).

Perhaps we could add a sentence along the lines of:

"The content of the level element contains identifying and/or descriptive text about the editorial status of the parent element."

Suggestions for better or more precise wording are appreciated!

**Comment by school510587** [comment]
@mdgood Thanks for your reply.

I think your suggestion has properly presented meaning of text value of a level tag. However, content of the value is free (application-dependent or manually written), which is mentioned in the paper and not included in your suggestion. It would be better to remind readers of the scope of the text value.

**Comment by mdgood** [comment]
@school510587 Thanks for the feedback. Do you have a suggestion for how that concept might be added? I thought that part would be clear since the element is defined as an xs:string and there are no standard values suggested as there are for some other xs:string elements (e.g. `<part-type>`).

EDIT for those reading later: I meant to write `<credit-type>`, not `<part-type>`.

**Comment by school510587** [comment]
@mdgood OK, sorry, I have just learned to read *.mod files by Notepad. Where can I find definitions such as xs:string?

I guess the answer is musicxml.xsd. However, I find that level has a way of definition different from other familiar elements such as work-title, which is intuitive to have no limitation on content of the text.

```<xs:element name="work-title" type="xs:string" minOccurs="0">```
```<xs:element name="level" type="level"/>```

Here, I can't find any link between `<level>` element and `xs:string`. What is the correct way to check this definition?

By the way, I can't find part-type in this file, either... Sorry, I don't know any high-level method to view these schema documentation files, which may confuse you a lot.

**Comment by mdgood** [comment]
@school510587 This will get much easier to follow when we have updated documentation for MusicXML 4.0, rather than having to read the schema files directly.

Anything with an xs: prefix, like xs:string, is a standard W3C XML Schema type. The xs connection is defined in the top-level xs:schema element:

`<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" elementFormDefault="qualified" attributeFormDefault="unqualified">`

When you see something like `type="level"`, that means you need to search for `name="level"` within the schema to find the type definition. That is where you will see the connection to xs:string.

The intent is that these connections will all be linked together in the documentation so it should become much easier to see what is going on.

You cannot find `<part-type>` because it is not there. My apologies! I meant to write `<credit-type>`.

I hope that this helps.

**Comment by mdgood** [comment]
@school510587 Pull request #373 addresses this issue. Could you please review it if you have a chance?

**Comment by school510587** [comment]
@mdgood OK. I think "identifying and/or descriptive" is clear enough to close this issue. Thank you for the reply and PR.
