### ISSUE TITLE
Override vs. Automatic

### ISSUE THREAD

**Issue by webern** [w3c/musicxml#176]
In my application I want to save both the state of something, for example stem direction, and also indicate in the file whether or not the stem direction is "frozen".  So for example, I might want to indicate in the file that the stem direction is UP, but that any subsequent layout or state changes to the note are free to change it.  Alternatively, I might want to indicate that the stem is UP, and that it should remain UP even if the note is moved or transposed, etc.

I think this is a case where my requirements, because I am using MusicXML as a native file format, may be outside the scope of MusicXML's purpose.  But I wanted to share it here because it is an example of something that an application might need to save which cannot be done properly with MusicXML.

The requirement to save "automatic" vs. "frozen" extends to many different types of state, not just stem up/down (the presence or absence of accidentals, for example).

For the stem direction, I have identified an element within the note that I expect is rarely ever used by the big notation programs, footnote.  Within footnote there is a font attribute which is a comma delimited list of strings.  I am stuffing my non-MusicXML state information into there.  I'm expecting any application that reads my files to just toss that gibberish out and hopefully not crash on it.

**Comment by mdgood** [comment]
Matthew, I think this issue duplicates #70 for stems and #108 for accidentals. Do you agree? If so, could you move this as a comment to #70, and then we can close this issue as a duplicate?

For non-MusicXML information, I highly recommend using XML processing instructions rather than reusing an existing MusicXML element, even if it seems rarely used. XML processing instructions were designed just for this situation. In this case, for instance, you could place something like:
`<?Komp stem="frozen"?>` before or after the `<stem>` element.

We use processing instructions in both Finale and the Dolet for Sibelius plug-in for both musical information not in MusicXML 3.0, and bug reporting about known problems in MusicXML export.

**Comment by webern** [comment]
Thank you for the tip about processing instructions, that is very helpful.  I agree this issue is duplicative of the other two that you linked.
