### ISSUE TITLE
Change uncompressed MusicXML file extension

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#191]
As we work on issues #50 and #51 regarding MusicXML media types and uniform type identifiers, we may want to take this opportunity to change the recommended file extension for uncompressed MusicXML files. Currently this is .xml which causes conflicts with other types of XML files. It could be more useful to have a unique, or at least less common, extension in order to help ease of use of uncompressed MusicXML files. We would keep the .mxl extension in place for compressed MusicXML files.

One of the more obvious extensions, .mxml, is already used by Adobe in their ActionScript / Flex products. We could use something longer like .musxml or .musicxml.

This effects the contents of both issues #50 and #51.

**Comment by cecilios** [comment]
shorter:   .umxl  (uncompressed mxl)

**Comment by mdgood** [comment]
Thanks - I like this idea. Other possibilities besides .umxl would include .mxlu, .mxlt, .xmlm. That would be u for uncompressed, t for text, or m for music, respectively. None of these 4-letter extensions seem to be used by other applications.

**Comment by mdgood** [comment]
At our Musikmesse meeting, @mogenslundholm suggested using .musicxml as the recommended file extension, since there is no need to keep file extensions to 3 or 4 characters. The group consensus was to go ahead with this. We will clarify that applications should also be prepared to see .xml as a file extension for older files.

**Comment by mdgood** [comment]
Pull request #206 addresses this issue.

**Comment by mdgood** [comment]
Since we will not be changing the media types in MusicXML 3.1, I am thinking we should also revert this change to the uncompressed file type and just leave it .xml. That is what is specified in our media type registration. 

I also took a look at implementing this in our software. It seems like quite a bit of work for perhaps not that much of a benefit in user experience. The confusion between applications supporting one suffix or the other may even make it a drawback.

What do people think? Would it be best to revert this to the .xml extension now? We can address having a unique uncompressed suffix in the future as part of the MNX work.

**Comment by ReinholdH** [comment]
I would like to object cancelling the decision which was made at the Musikmesse in Frankfurt to introduce the new extension .musicxml and re-discussing the topic now. 

At the Musikmesse I was the only one who brought up concerns about the impact to existing applications, compatibility and existing files to users. After some arguments it was clearly pointed out to demonstrate the importance of MusicXML with the new extension and to move forward. Please listen to the video of the meeting (MusicXML meeting - MusikMesse 2017 - part 1 at https://www.w3.org/community/music-notation/ from 17:47 to 20:20). The meeting minutes clearly point out the decision ("... The meeting reached consensus that we should make these changes, and a preference for .musicxml as the recommended file extension.") 

Based on this decision we at Notation Software (www.notation.com) fully implemented the new .musicxml extension meanwhile and completed all development work for our next release update. You can imagine that after all the discussion and our implementation work it is really no fun at all to cancel the decision from the meeting where full consensus was reached.

**Comment by adrianholovaty** [comment]
My two cents: we should make the change to the .musicxml extension. It will be a short-term pain (multiple extensions for users to know, plus more work for software developers) for a long-term gain (an unambiguous file extension).

**Comment by mogenslundholm** [comment]
Sad. It would have been an advantage for my users with the .musicxml-extension. They could associate it to my program and the open-dialog could show the relevant files. Also they could easily identify the files: This is a MusicXML-file because the extension is .musicxml

Once I made a new open-dialog, which scanned the files to show only MusicXML-files, but Apple didn't like that - called it "non standard". And I dropped the idea for the PC also.

But a .musicxml-extension would solve the problem, without setting new limitations - the .xml-extension may still be used. I can't see any problems with this. And the programming effort is nothing.

**Comment by jsawruk** [comment]
I agree with @adrianholovaty . Even though we aren't changing media types, I think using a different file extension (I like .musicxml) would cause less confusion and clearly separate MusicXML files from generic XML files. Instead of solely using .musicxml, perhaps would could support both .xml and .musicxml, but prefer .musicxml and deprecate .xml. 

I'm not sure what issues @ReinholdH ran into when adding support for .musicxml, but I agree with @mogenslundholm that the development effort should be minimal for most developers, and any pain points should be short term.

**Comment by mogenslundholm** [comment]
My programming effort for the PC was this (Standard open dialog in Windows):

  OpenDialog.Filter:=
      'Midi and MusicXML Files (&#042;.mid,&#042;.midi,&#042;.xml,&#042;.musicxml) | &#042;.mid;&#042;.midi;&#042;.xml;&#042;.musicxml | '+
      'Midi Files (&#042;.mid,&#042;.midi) | &#042;.mid;&#042;.midi | '+
      'MusicXML Files (&#042;.xml,&#042;.musicxml) | &#042;.xml;&#042;.musicxml';

Where "&#042;.musicxml" is  added in four places. This should be alike in all programming languages (This is Pascal).  This filter allows you to see either both MIDI and MusicXML files, just MIDI or just MusicXML-files. Opening only MusicXML, only the last line is needed. It is different in MAC, but just as simple.

**Comment by mdgood** [comment]
Thank you for all the feedback. We will keep the .musicxml extension then. I will re-close this issue and leave everything as-is in the current MusicXML 3.1 beta.

**Comment by mogenslundholm** [comment]
Thanks.

**Comment by ReinholdH** [comment]
Thanks
