### ISSUE TITLE
Clarify best practice for redundant tab staves

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/musicxml#205]
Out there in the Wild West of music notation programs, I've seen tablature in MusicXML specified in three ways:

1. Separate `<part>` elements for the standard-notation stave and the tab stave — essentially treating them as semantically distinct.
2. A single `<part>` containing both the standard notation and tab, using a `staff-number` for relevant elements to distinguish which bits are on the notation vs. tab stave.
3. A single `<part>` containing both the standard notation and tab, _without_ using `staff-number`.

Each approach has its benefits and drawbacks. I have two requests of the community:

1. Can we devote some space in the documentation to these benefits and drawbacks, and possibly suggest a best practice? I fear that people making MusicXML exporters don't fully understand the subtle differences between these approaches.
2. In the first case (number 1 above, separate `<part>` elements), could MusicXML perhaps give some hint that a given tablature `<part>` represents a given non-tab `<part>`? As it stands, the only way to unify the parts is to perform heuristics (which is what [Soundslice](https://www.sounslice.com/) does, because our data model unifies tab and notation).

FWIW, my own philosophy on this is: the standard-notation and tab staves describe the _same music_, so it should semantically exist as only one `<part>`.

**Comment by cyrilcoutelier** [comment]
I agree with Adrian regarding the need for a best practice, and the idea that standard-notation and tab staves should go into the same part.

**Comment by mdgood** [comment]
I think the best practice is to have a single `<part>` with the 2nd staff marked not just with a staff number but also by a `<staff-type>alternate</staff-type>` element to indicate that the 2nd staff is an alternate representation of the 1st staff, rather than an additional sounding staff. You could even do that with two separate parts.

Sometimes it may not be practical to have a single part due to the software modeling the two staves as separate instruments. So while 2 seems like the best choice, choice 1 can work reasonably well too.

I don't know though if any notation software actually uses the alternate value for the `<staff-type>` element yet. I think that would provide the semantic link that you are requesting.

Thank you @adrianholovaty for raising these tab documentation issues. If you can find a way to clarify these interconnected issues and create a pull request, I would be happy to add these into scope for V3.1.

**Comment by adrianholovaty** [comment]
@mdgood Almost a year later, I'm working my way through my old to-dos and found this. I'd be happy to update the documentation, but I'm not sure where I'd do that — can you point me at the appropriate file?

**Comment by mdgood** [comment]
And now 2 years later I think we will finally do this, @adrianholovaty! I think the documentation for the staff-type element (DTD) or simple type (XSD) would likely be a good place for this. That would be in attributes.mod for the DTD and musicxml.xsd for the XSD. However I expect this would be addressed together with related issue #292, so I am happy to make the updates if you and @cyrilcoutelier can review them.

**Comment by mdgood** [comment]
Pull request #372 addresses this issue. @adrianholovaty and @cyrilcoutelier, would you be able to review this? Thanks again for raising this issue.

**Comment by cyrilcoutelier** [comment]
Looks good to me! 

When we will update the system to explore the specs with examples, we will then be able to populate with examples that will serve as recommendation, especially for the representation of normal staff vs TAB staff for elements like bends or harmonics.
