### ISSUE TITLE
Duration in harmony

### ISSUE THREAD

**Issue by Bigsby** [w3c/musicxml#220]
Harmony should have, as it actually does have, duration properties, like any other note.

**Comment by mdgood** [comment]
This is an interesting idea but incompatible with the way the MusicXML currently works. Could you please raise this as an issue, with more rationale for this proposal, in the [MNX repository](https://github.com/w3c/mnx)? MNX is where we are considering these types of incompatible changes to how MusicXML currently works.

Specifically, should harmony be considered a span-type direction as discussed in [MNX issue 12](https://github.com/w3c/mnx/issues/12)? Dynamics are another area where notation happens at a single point that affects playback afterwards.

**Comment by Bigsby** [comment]
Thank you for, once again, directing. I didn't know about MNX. On my way.

Could you, please, enlighten my regarding "the way the MusicXML currently works" that makes the idea incompatible?

**Comment by mdgood** [comment]
@Bigsby I apologize for the long delay in answering your question. Currently the `<harmony>` element signifies a change in harmony and does not have a duration. This is similar to how the `<dynamics>` element works in MusicXML.

It might be a good idea to change this in MNX, either to have a duration, or to indicate explicit start and stop points in a span-type direction. However, these approaches would be incompatible with the way that MusicXML software already works. This is why I believe we should reserve consideration of this issue for MNX rather than MusicXML.
