### ISSUE TITLE
Dot as part of duration

### ISSUE THREAD

**Issue by Bigsby** [w3c/musicxml#221]
Despite the separation of MIDI data and display data, it makes more sense that the elements relative to a particular property, e.g. duration, to be in the same wrapping element. For instance:

```xml
<note>
  <duration>
     <units>384</units>
     <dot />
  </duration>
</note>
```

It would also make the duration type usable in other scenarios, like harmony.

**Comment by mdgood** [comment]
This is an even more incompatible change than including durations in harmony elements. It seems beyond the scope of MusicXML but something to consider in [MNX](https://w3c.github.io/mnx/overview/). I believe the current CWMNX proposal does something similar to this but with some different syntax.

**Comment by Bigsby** [comment]
I'm confused with "beyond the scope of MusicXML". Never the less, I was quite wrong in changing duration element which represents the "MIDI" duration. The place for the dot should be in note-type..

**Comment by Tails** [comment]
+1

**Comment by mdgood** [comment]
Future versions of MusicXML need to maintain compatibility with older versions of MusicXML in order to maintain MusicXML's interoperability and archival qualities. One of the reasons for starting the MNX project is to create a next-generation notation standard that is not bound by these compatibility constraints.
