### ISSUE TITLE
Unclear where <mute> element can be placed

### ISSUE THREAD

**Issue by Tails** [w3c/musicxml#238]
I work on parsers from Guitar Pro to Musicxml (so mostly the guitar interpratation) but it is unclear where the mute element is allowed to be placed. Does it go in measure? Note? Note/technical?

See: https://github.com/w3c/musicxml/blob/af6380bd23e6e6d35844b27d39276e033a4d9626/schema/common.mod#L1115

**Comment by jsawruk** [comment]
If I understand the schema correctly, `<mute>` is a child element of `<play>`, which is a child element of `<note>`.

Example:

    <note>
      ...
      <play>
        <mute />
      </play>
    </note>

**Comment by Tails** [comment]
But was does it mean then if it is under ```<play>```? That one should "play" the note muted? Or that it is performance information? That one should at a certain moment in time mute the instrument because... 

The element specifies the way of muting, for example, with palm or other limbs and technical ways, so I supposed it was a semantic element unrelated to hints for software players.

(I am looking for a semantic encoding of palm muting a guitar note and thought I had found it in this).

**Comment by jsawruk** [comment]
> The play element, new in Version 3.0, specifies playback
	techniques to be used in conjunction with the instrument-sound
	element.

It appears that the `<play>` element only specifies the sound for playback. It does not include notations, which occur in the `<notations>` element, specifically `<technical>`. However, when I look at the schema, there is no technical notation specifically for palm muting. Palm muting notation for a guitar is different mute notation for a brass instrument. 

https://github.com/w3c/musicxml/blob/af6380bd23e6e6d35844b27d39276e033a4d9626/schema/note.mod#L813

I suggest we add a way to represent palm muting. I'm not sure it belongs in `<technical>` though, because it can apply to multiple notes the same way an 8va can. Maybe it should be under `<direction-type>`, where `<string-mute>` already exists.

It might be possible to add to the `<string-mute>` element to support palm muting as well. I agree with you that the semantics should be clearer; I just am not sure where a solution would be most effective.

**Comment by mdgood** [comment]
This appears to duplicate issue #103, which explicitly mentions palm mute as something that needs better semantic representation.

**Comment by mdgood** [comment]
I am closing this issue as it is a duplicate.
