### ISSUE TITLE
Question: correct use of repetition marks

### ISSUE THREAD

**Issue by cecilios** [w3c/musicxml#252]
I would appreciate some guidance for using repetition marks in the following example. It is taken from Gardner Read's book, example 12.3 (3), page 229:
```
        Segno                        DC al Segno
|-------|--------|-------||-------|----------||
 1       2        3        4       5       
```
Playback order: 1,2,3,4,5 -> 1 -> 4,5

How this would be encoded in MusicXML? Is the next encoding correct?
```
<measure number="2">
	<direction placement="above">
		<direction-type>
			<segno/>
		</direction-type>
		<sound dalsegno="S1" times-only="2" />
	</direction>
	...
</measure>
...
<measure number="4">
	<sound segno="S1"/>
	...
</measure>
...
<measure number="5">
	...
	<direction placement="above">
		<direction-type>
			<words>D.C. al Segno</words>
		</direction-type>
		<sound dalcapo="yes"/>
	</direction>
</measure>
```

**Comment by mdgood** [comment]
That Read example does not seem like standard notation practice these days. In measure 2 you would use something like `<sound tocoda="S1"/>`. You don't need the time-only attribute, because 2 is the default for the tocoda attribute. In measure 4 you would have something like `<sound coda="S1"/>`. In measure 5 you would have `<sound dacapo="yes"/>`. Note that the attributes are dacapo vs dalcapo, and time-only vs times-only.

I hope this helps!

**Comment by cecilios** [comment]
Thank you very much for your explanation.

Apart from the typos in attributes names, then I understand that my encoding is valid and the only difference with yours is that you preferred to use `tocoda` instead of `dalsegno` because it implies `time-only="2"`. Is this correct?

If so, I understand that there are no particular rules for using these attributes (i.e `dalsegno` vs `tocoda`), even they do not have to match any associated `<direction>` and the only rule is that targets must be paired (i.e. use `tocoda`for a `coda` destination label). If this is true, I would propose to deprecate attributes `tocoda, dalsegno and dacapo` and replace them by a `goto` attribute, and deprecate `segno and coda` attributes and replace them by a `label` attribute:
```
<sound tocoda="coda1"/> = <sound goto="coda1" time-only="2"/>
<sound dalsegno="segno1"> = <sound goto="segno1"/>
<sound dacapo="yes"> = <sound goto=0>

<sound segno="S1"/> = <sound label="S1"/>
<sound coda="C1"/> = <sound label="C1"/>
```
This will simplify the MusicXML language, make it more clear and more open for other use cases, and avoid several alternatives for encoding the same information.

**Comment by mdgood** [comment]
I apologize that I was unclear in my previous reply. There are rules for using these attributes, and your original encoding was not correct. The `tocoda` and `coda` attributes are used for forward jumps. The `segno` and `dalsegno` attributes are used for backward jumps.

That is why I said the Read example does not seem like current standard practice. It is using the segno sign for a forward jump rather than a backward jump.

**Comment by cecilios** [comment]
Thank you. I missed the forward jumps and backward jumps issue. Now it is clear.

Thank you.
