### ISSUE TITLE
Error importing MusicXML 3.1 with Dolet 7.1

### ISSUE THREAD

**Issue by pgabr** [w3c/musicxml#253]
I have a sffzpp dynamic in Maestro font in Finale 14.5 
I export it to musicxml 3.1 with Dolet 7.1,
when I edit the file, it is described as ≤other-dynamics≥sffzpp≤/other-dynamics≥
so far, so good, BUT...
when I import it with Dolet 7.1 in Finale 2011, the sffzpp has disappeared!

temporarily solution:
I have to define the sffzpp dynamic with a text font (like Times),
I export it to musicxml 3.1 with Dolet 7.1,
when I edit the file, it is described as ≤words default-x="61" default-y="-26"≥sffzpp≤/words≥
when I import it with Dolet 7.1 in Finale 2011, the sffzpp is there

apparently not all dynamic combinations are supported in other-dynamics import...

**Comment by mdgood** [comment]
Sorry for this problem. This isn't an issue with MusicXML 3.1, but with the Dolet for Finale plug-in's implementation. From your description, I suspect this is also an issue in the latest Finale v25.5's MusicXML support.

Since this is a Finale problem, could you please file this problem report at the Finale customer support site at http://www.finalemusic.com/support/? Click on the "Ask A Question" button and fill in the details. If you can attach your original Finale file with the sffzpp dynamic that would be very helpful. Please also mention that I have requested that customer support forward the issue on to me for fixing. Thanks so much for your assistance in improving how MusicXML interchange works.

This repository is for issues with the MusicXML format itself, rather than individual implementations of MusicXML. Problems with a particular software application's MusicXML implementation are best reported to the developers of that application. Thanks!

**Comment by mdgood** [comment]
I am closing this is this was a Finale / Dolet problem. For reference, this was fixed in Finale v26.0 and Dolet 7.2 for Finale.
