### ISSUE TITLE
Versioning question

### ISSUE THREAD

**Issue by orange-tsai** [w3c/musicxml#255]
Does a tool exist for the automatic conversion from MusicXML 1.1 -> 2.0 ? or from all previous versions to the latest?

**Comment by mdgood** [comment]
This generally isn't necessary since all valid MusicXML 1.1 files are valid MusicXML 2.0 files. The same is true with all versions from MusicXML 1.0 to MusicXML 3.1. All valid files in earlier MusicXML versions are also valid files in later MusicXML versions.

There's one small exception in MusicXML 3.1 where some attributes were removed that had been included by mistake in an earlier version and were never used by any applications. See #140 and #155 for more details. In practice applications needs not worry about this.
