### ISSUE TITLE
Adding a XML catalog file

### ISSUE THREAD

**Issue by PhilippeCuvillier** [w3c/musicxml#259]
XSD and DTD files are great tools for MusicXML validation. And performing validation is straightforward with XML processing libraries and command line tools such as xmllint.
But when trying to do so, at first place people will usually run into the issue of external DTD loading:
``bash
warning: failed to load external entity "http://www.musicxml.org/dtds/partwise.dtd"
``

This is why I suggest adding a XML catalog file to this repository. Such XML catalog would make validation with local copies of DTD and XSD files very easy. People could just download the latest release of this repository to get the local copies, and run any validation using this file. Such operations would become truly straightforward even for people un-familiar with XML.

A first proposal for such XML catalog is this one: it simply replace the external URI with the local URI of the `schema` folder of this repository:
https://github.com/PhilippeCuvillier/musicxml/blob/e7a089da888bd616a069f5f6d34c697df7d03177/catalog.xml#L1-L13

Another proposal is a more "complete" XML catalog:
https://github.com/PhilippeCuvillier/musicxml/blob/e7a089da888bd616a069f5f6d34c697df7d03177/catalog-full.xml#L1-L28
To use it, one should just replace the two `xml:base` attributes value with the URI of their local copy of `schema` folder.

**Comment by mdgood** [comment]
Thank you for this suggestion. Do you know how widespread is XML catalog support in software tools these days? The last time I looked at this, support was very intermittent. However that was a very long time ago.

You can solve these problems in most languages by using entity or resource resolvers. But as you say, that is more complicated than would be ideal.

**Comment by PhilippeCuvillier** [comment]
Thanks for your answer. I really think XML catalog is pretty standard now :
- Java API supports them (by an EntityResolver extension called [CatalogResolver](https://docs.oracle.com/javase/9/docs/api/javax/xml/catalog/class-use/CatalogResolver.html)).
- libxml [does so](http://xmlsoft.org/catalog.html).
- its Python version lxml does it [too](http://lxml.de/resolvers.html).
- same for all [Saxon products](https://www.saxonica.com/html/documentation/sourcedocs/xml-catalogs.html).
- Oxygen editor integrates catalogs [very well](https://www.oxygenxml.com/doc/versions/20.0/ug-editor/topics/using-XML-Catalogs.html). When opening an Oxygen project file, It evens looks by itself for a `catalog.xml` in the same folder and loads it automatically for validation, XSL transforms, XSpec unit test, etc.

As for the other languages I do not know. But so far I think it definitely worth it.

**Comment by mdgood** [comment]
@PhilippeCuvillier Thank you again for this suggestion. To help us consider this for MusicXML 3.2, would you be willing to join the W3C Music Notation Community Group? You can join by going to our home page at https://www.w3.org/community/music-notation/ and clicking the Join Or Leave This Group button. Please be sure to join on behalf of your organization - Antescofo should already be set up in the W3C system. Thanks!

**Comment by mdgood** [comment]
Pull request #384 addresses this issue, as well as several other discussions about making validation easier for developers. 

Earlier we made a change in issue #285 from absolute to relative URIs. Relative URIs do not work very well with XML catalogs, so this pull request is reverting that change. Using XML catalogs seems like the better solution to the overall issue.

Similarly, pull request #344 attempts to address the validation issue by changing the http to https in the system IDs and URIs. Again, XML catalogs seem like a better way to solve the problem.

Could those of you who have run into these issues - including @deepio, @infojunkie, @PhilippeCuvillier, @roewenstrunk, @tjwrona1992, and @webern - please review this pull request and make sure this is working for you? I have tested this in Java and Python implementations and all seems to be working, whether the device doing the validation is on or off the network.

If anyone has questions about getting XML catalogs working, please feel free to raise them here. We want to be sure we can get things working on different development platforms.

Thanks again for all your help in raising these issues and proposing different solutions. I am looking forward to having this pain point fixed in MusicXML 4.0.

**Comment by infojunkie** [comment]
I was able to successfully validate using PR #384 and the following `xmllint` invocation:
```
XML_CATALOG_FILES=schema/catalog.xml xmllint --schema schema/musicxml.xsd ~/src/infojunkie/ireal-musicxml/test/output/Corcovado.musicxml --noout --nonet
```

Sounds like a great solution!

**Comment by mdgood** [comment]
Has anyone else had a chance to test this yet? I plan to merge the pull request and close this issue early next week unless we hear of problems or questions. Thanks!
