### ISSUE TITLE
Helmholtz-Ellis Accidentals for Just Intonation

### ISSUE THREAD

**Issue by 000masa000** [w3c/musicxml#263]
Is there any possibility of including the Extended Helmholtz-Ellis JI Notation microtonal accidentals, which are already part of the Bravura Font and smufl, into a future update of MusicXML? I am currently working on improving the polyphonic microtonal playback feature offered in musescore so that it can be driven by accidentals, so it is possible to have automatic microtonal and JI playback from notation. Dorico, for example, is offering a similar support of microtonal playback but in a different way. Would be great if the accidentals could be transferred via MusicXML between platforms and then play back in both environments. 
Marc Sabat

**Comment by mdgood** [comment]
Marc, I believe what you are looking for is already available in MusicXML 3.1. The `<accidental>` and similar elements like `<accidental-mark>` and `<key-accidental>` now have a smufl attribute where you can specify the exact SMuFL glyph for any of the accidental ranges. For most of the Extended Helmholtz-Ellis range, you probably want to use "other" as the value for the accidental element, e.g.

`<accidental smufl="accidentalFlatThreeArrowsUp">other</accidental>`

If one of MusicXML's standard accidental values matches the sound but not the appearance, you can use that value instead instead of "other".

You will want the `<alter>` element to specify the microtonal value in addition to the `<accidental>` element for the best chance that applications can interpret one or the other correctly.

Does this match what you are looking for?

**Comment by mdgood** [comment]
@000masa000 Did the existing MusicXML 3.1 features work for you? Or is there something additional that you believe is still needed to get this working well? Thanks!

**Comment by mdgood** [comment]
I am closing this issue as I believe it is working in MusicXML 3.1. If there are problems please let us know so we can reopen the issue.
