### ISSUE TITLE
String Number Display

### ISSUE THREAD

**Issue by snakebyte69** [w3c/musicxml#267]
MusicXML captures the string and fret location, however there doesn't seem to be a mechanism to indicate if the string number is to be displayed in the score. Adding a toggle to the string element would fix this. e.g. Display=yes/no. Something more elegant could be used of course.

**Comment by jsawruk** [comment]
Could you please provide a notation example? It would help in understanding this particular situation. Thanks.

**Comment by snakebyte69** [comment]
![string number2](https://user-images.githubusercontent.com/39090848/52456246-f7e4a380-2ba7-11e9-8d86-72e5892f8f8b.jpg)

**Comment by mdgood** [comment]
I think this is closely related to issue #205 regarding redundant tab staves. If the staves are not redundant, then a `<string>` element is displayed as appropriate for each standard or tab notation.

You can keep a `<string>` from displaying in standard notation by putting it in a `<notations>` element that does not display:

`<notations print-object="no>
  <technical>
    <string>6</string>
  </technical>
</notations>`

This works for a standard notation staff. However if there is one staff displaying both standard notation and tablature, this may not work so well. In our discussion of issue #205, we seemed to be coming to agreement that this should not be the recommended practice.

If there is something I have missed or misunderstood, please let me know.

**Comment by snakebyte69** [comment]
This issue is that the string number is NOT displayed in standard notation, when exported to MusicXML and then imported again. It's redundant in the TAB staff as the lines already represent the strings.

I have looked up "print-object" the fact it's version 3 is the issue. Programs like GuitarPro are still on version 2.

This would be the solution.
"notations print-object="yes" technical string 6  string  technical  notation"

I will bring this to their attention.

**Comment by adrianholovaty** [comment]
Adding some extra context here...

In tablature notation, by definition, you have a string number and a fret number for each note. In standard notation, string numbers are optional editorial markings, similar to piano fingerings; they're conventionally rendered as a number within a circle.

The [notation screenshot above](https://github.com/w3c/musicxml/issues/267#issuecomment-461672514) is a tiny bit misleading, because each note in the standard notation has a string number provided. More realistically, a staff would have string numbers only when it's non-obvious (unless it's an educational/beginner score) — again, like piano fingering.

I agree with @mdgood that this is related to #205. We need to be able to handle three distinct cases, depending on whether tablature data is in a separate staff:

1. **No tablature staff, only a standard notation staff.** "This is the string number for this note, and please do not interpret it as tablature."
2. **Tablature staff plus standard notation staff.** The tablature staff's markup includes the string number for every note, but the standard notation staff only includes the string number where necessary.
3. **Single staff containing both tablature and standard notation data.** Here, we have ambiguity. In this case, there doesn't seem to be a clear way to specify whether a given fingering should be displayed in the standard notation.

**Comment by snakebyte69** [comment]
In classical guitar notation (no TAB) string numbers are commonly used for complex pieces as certain fingerings make a huge difference from a technical perspective.

e.g. trying playing a fast 3 note per string passage using 2 notes per string.

I think you should focus on case 1 and 2, string numbers don't need to be presented in the TAB staff.
e.g. 5 on the 6th string in TAB clearly tells us which string, we don't need an additional 6 in a circle.

example 2 - This would be useful to notate a piece of music in TAB and use that to generate Classical Guitar notation. This would be extremely useful for educational purposes.

example 3 - You don't need a sting number in a circle, we clearly know from the TAB which string is being played.

**Comment by mdgood** [comment]
I think that #205 has resolved this issue, so I will close it. The only problem happens when a single staff is containing both tablature and standard notation. We have clarified this is non-standard behavior. 

In the cases that MusicXML support, the `<string>` element is used in tab to determine the placement of the note on the correct line of the tab staff, and to display a circled number in standard notation. This behavior has been constant since MusicXML 1.0.
