### ISSUE TITLE
Add part name as a standard credit-type value

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#282]
The `<credit-type>` element indicates the purpose behind a credit. Any string can be used within the element value, but standard MusicXML 3.1 values are page number, title, subtitle, composer, arranger, lyricist, and rights.

Part names are another common type of data represented in MusicXML `<credit>` elements. Adding "part name" to the list of standard MusicXML credit-type values would help improve the transfer of parts between applications.

**Comment by jsawruk** [comment]
@mdgood Could you please provide an example? I'm trying to understand this use case better, and I'm not sure that "part name" is semantically related to `<credit>`.

I think what you're referring to is the part name that would usually appear in the upper left hand corner of an individual part. I understand how this concept is distinct from the name of part within a score (`<part>`). I also understand that you're grouping these elements under `<credit>` because they are visually related, but they don't feel semantically related. Could you expand on how adding part name as a `<credit-type>` would improve the transfer of parts among applications? I feel like there's a semantic use case beyond a visual element that I am missing.

**Comment by mdgood** [comment]
Good questions @jsawruk - thanks for raising them.

The `<credit>` element handles text that is not semantically connected to a single position in the music. Often these are actual credits like the composer and copyright, but it is not limited to that one type of metadata - we already have a standard `<credit-type>` value for "page number". 

Apps that implement the `<credit-type>` element usually make use of an app feature that connects text to metadata. Sibelius has [wildcards](https://www.scoringnotes.com/tips/unleash-power-text-wildcards/), Finale has [text inserts](https://usermanuals.finalemusic.com/FinaleMac/Content/Finale/sub-inserts.htm), and I am sure many other notation editors have a similar concept.

Like page number, part name is a common type of metadata that applications identify in their text handling. Both Sibelius and Finale use it for instance as a type of wildcard or insert. 

This issue is not meant to exclude expanding the standard credit-type values even further. I've already seen one email request for a "dedication" value for example. This particular metadata is especially important for transferring both score and parts between applications. So it seemed to be worth calling out as a separate issue.

I hope this clarifies the motivation. If not please follow up with more questions!
