### ISSUE TITLE
Add support for swing

### ISSUE THREAD

**Issue by cyrilcoutelier** [w3c/musicxml#283]
I think we need some semantic to direct how to swing notes in the playback. 
It should go into a sound element. 
We need to specify the level of notes that are swung: 8th 16th or none. 
And we need to specify the way time is divided between the two notes. 

Here are some proposals on how it could look like: 

``` xml
<!-- No swing -->
<sound>
  <swing>  
    <type>no</type>
  </swing>
</sound>

<!-- 8th swing -->
<sound>
  <swing>  
    <type>8th</type>
    <left-duration>2</left-duration>
    <right-duration>1</right-duration>
  </swing>
</sound>
```

**Comment by adrianholovaty** [comment]
This gets a +1 from me. MusicXML does already support this (indirectly) via `<metronome-note>`, but it would be much easier to parse, and more semantic, if the format dealt with swing at a higher conceptual level.

**Comment by jsawruk** [comment]
Agreed, I think this is a good proposal. I'm not sure how it would look as markup yet, but I do like the idea that @cyrilcoutelier presented of specifying the swing type/ratio. This could also extend beyond jazz to other interpretation, like notes inégales.

**Comment by amypellegrini** [comment]
I add to this! I just wonder if any additional flexibility would be good for potential edge cases, I'm thinking specifically about the actual definition of Swing, which is not necessarily defined as a perfect ternary division, but rather as a visceral manipulation of time values which may not be as precise.

For example:

It may be that in order to achieve the specific swing time feel that I intend to express, I choose a ratio of 3:2, so I would subdivide the time unit into 5 subdivisions, of which the sum of 2 subdivisions would give me the actual shorter note duration I want to express.

**Comment by mdgood** [comment]
This would supplement the `<metronome-note>` and similar elements. Those elements specify the visual appearance of swing and other metrical relationships, but not the playback.

The original MusicXML design idea was that swing and notes inégales could be specified using the duration element. But nobody does that; it's not how most music notation software work.

I think that the proposal from @cyrilcoutelier handles the case that @amypellegrini brings up:

```
<!-- 8th swing -->
<sound>
  <swing>  
    <type>8th</type>
    <left-duration>3</left-duration>
    <right-duration>2</right-duration>
  </swing>
</sound>
```

If I am misunderstanding something, please let me know.

**Comment by mdgood** [comment]
At the Community Group online meeting, Daniel Ray suggested possibly using "an interpretation value from a global list (ex: Samba, Shuffle, etc.) and it would be up the various software solutions on how to apply this." 

While this more closely matches the UX of several notation editing applications, I don't think it is as flexible for use by a wider range of applications. The numeric relationship in particular would help in knowing exactly what is intended for playback use.

It might well be useful to add an optional element or attribute, perhaps called style-name, for the name of the swing style being used in the encoding application.

**Comment by mdgood** [comment]
Here is what I am currently thinking of doing, with some questions for everyone. It's pretty close to @cyrilcoutelier's original proposal, with a few adjustments.

I'm thinking of adding a `<swing>` element as a child element of the `<sound>` element, with a DTD definition that looks like this:

`<!ELEMENT swing ((straight | (first, second, swing-type)), swing-style?)>`

Cyril's examples would then look like this:

``` xml
<!-- No swing -->
<sound>
  <swing>  
    <straight/>
  </swing>
</sound>

<!-- 8th swing -->
<sound>
  <swing>  
    <first>2</first>
    <second>1</second>
    <swing-type>eighth</swing-type>
  </swing>
</sound>
```

The advantage of this definition is that it makes the elements specifying the ratio required whenever some variation of swing is specified. The XSD will specify positive integers for the content of the `<first>` and `<second>` elements.

In both cases you can add an optional `<swing-style>` element at the end, whose text content is the name of the application's swing style.

My questions are:

1. What names would we prefer for the child elements? I think `<swing>` is good for the main element, but I don't have strong feelings about the children. I do think names specific to the `<swing>` element would be good, so I changed `<type>` to `<swing-type>` in this proposal.
2. Do we need anything besides "eighth" and "16th" for the values of the `<swing-type>` element? I changed 8th to eighth to be consistent with the values we use in the `<type>` element.
3. Should the `<swing-type>` element be optional, with a value of eighth assumed if not present?
4. Should we require that the value of the `<first>` element be greater than that of the `<second>` element? We can't validate that with an XSD but we can still specify it. Many (most? all?) notation applications put this restriction into their user interfaces.

**Comment by mdgood** [comment]
If @cyrilcoutelier, @adrianholovaty, @jsawruk, @amypellegrini, @gierschv, or anyone else has some thoughts on any of the questions raised above, those would be most appreciated!

**Comment by cyrilcoutelier** [comment]
I agree with the proposal. 
1. I am Ok with the names
2. I have heard of users only asking for 8th and 16th, although I am not 100% sure there is not anything else in the wild
3. I would say yes, as most swing I heard of is with 8th
4. I don't mind it being mandatory, especially if most does it, and if the opposite doesn't exist in the wild

**Comment by adrianholovaty** [comment]
1. The names look good.
2. I can't think of anything other than eighth or 16th notes. The underlying design supports other values, though, so we can always add other allowed values in the future.
3. Sure, having a default of eighth notes seems reasonable.
4. If I understand the question correctly, then I think my answer would be _no_. Here's a screenshot of the swing settings allowed by Guitar Pro, and the "Scottish" settings have the second number higher than the first. I have no idea how common this notation is in practice, but we at least have a tangible example of software that supports it.

<img width="252" alt="Guitar Pro screenshot" src="https://user-images.githubusercontent.com/180401/98360470-29fb9180-202a-11eb-92f0-2b7b5755bb91.png">

**Comment by mdgood** [comment]
Thanks so much @cyrilcoutelier and @adrianholovaty for the great feedback. This really helps for putting together a pull request. If anyone else has thoughts on this please share!

I think the remaining issue is to specify how this interacts with the `<duration>` element and the attack and release attributes for the `<note>` element. My current thinking is that a `<duration>` value that differs from the nominal value used with the corresponding `<type>` element overrides the swing setting. The attack and release attributes are currently specified as modifying the flow of durations. We can adjust that to say it modifies the swing-adjusted value if the duration value matches the nominal setting for the `<type>` element. 

Does this seem good? That may be easier to answer in the context of an actual pull request, so I will get started on putting that together.

**Comment by jsawruk** [comment]
I agree with what @adrianholovaty wrote. 

Some thoughts:

- I think `<swing-type>` should allow any note value, just for flexibility. I don't know of any music where quarter notes would have an uneven feel, but it could happen. Also, I think swing 32nds could be a thing.

- Would it be possible to have different swing values for different durations, i.e. eighth notes and 16th notes have different ratios?

- We should document how the ratio should be interpreted, and how to "normalize" a ratio. While we can't constrain it in the XSD, I think the ratio should be expressed in lowest terms. Also, if someone really wants a 2.4 : 1 ratio, we should describe how to convert that to the integer ratio of 12 : 5. This is just a documentation recommendation, but I think it would be helpful.

**Comment by mdgood** [comment]
Thanks @jsawruk! My thoughts on your thoughts:

- My current thinking is that it is easier to add something later than to take it away. I am inclined to restrict the `<swing-type>` value for now, both to better capture how this feature is used and to reduce unneeded application complexity.
- Simultaneous different swing values for different durations would not be supported in this design. If we wanted to add that in the future I think we could allow multiple `<swing>` elements per `<sound>` element. For now I think it best to leave it out, again to reduce complexity.
- Yes, this is a great point and I agree that the ratio should be expressed in the lowest terms. 

Note that high-resolution performance applications can still use the older MusicXML approach of exactly specifying duration, attack, and release values for each note. So the unusual cases can be represented in MusicXML, just not at the more semantic and general level that the `<swing>` element provides.

**Comment by jsawruk** [comment]
@mdgood Sounds good!

**Comment by mscuthbert** [comment]
Notes inégales (which has an excellent Wikipedia entry -- https://en.wikipedia.org/wiki/Notes_inégales) are basically the same as swing notes.  As far as I know they only ever appeared on eighths or 16ths, so no additional need for extra features there, but the interpretation of dotted notes might need to be specified.  Even into the 20th c. (band marches) there is a tradition that in French music, a dotted eighth sixteenth is performed closer to double-dotted eighth + 32nd.  Is this possible to specify?  Perhaps does not need to happen here, since as @mdgood notes, higher-resolution applications can use the older MusicXML approach.  What should be clarified is what should happen on a note that has a general `<sound><swing/></sound>` tag but also has a specific duration/attack/release value?  Does the swing value get applied on top of that value?  My sense is No:  specific duration/attack/release values override swing completely.

**Comment by mdgood** [comment]
Thanks @mscuthbert. My thinking is that we do indeed leave the dotted rhythm issues to the current MusicXML approach of exactly specifying durations.

However, as I mentioned earlier, I think we may want to let attack and release values modify the swung duration. Otherwise it might make it more difficult for applications to specify a more staccato playback of a swung rhythm, for instance. Swing would not apply if the duration value is different than the nominal value associated with the type of a note. The swing playback would also not apply for notes where a type element is not present, or to grace notes.

I am not at all sure that this is the best decision though. I would be most interested to hear other opinions and rationale for this for either approach!

Also, how should we specify the notes to which the swing applies? I was thinking "consecutive notes" but that seems too general. Would "consecutive on-beat / off-beat notes" be better? That seems more applicable to eighth notes but I'm not sure of a better way to generalize to 16th notes. Suggestions are most welcome here as well!

**Comment by mdgood** [comment]
I have created a preliminary pull request #346 for implementing swing playback. Sometimes it can be easier to evaluate different choices by seeing a concrete proposal. Comments and suggestions on any part of the pull request and the swing feature are most welcome.

**Comment by mdgood** [comment]
There hasn't been anything new in the past few days, and my prototyping work with #346 has worked fine with no issues. Unless something comes up I will plan to merge this tomorrow morning California time. We can always refine things later in the 4.0 cycle if we want.
