### ISSUE TITLE
Editorial brackets and parentheses that span several symbols

### ISSUE THREAD

**Issue by hhpmusic** [w3c/musicxml#288]
MusicXML 3.1 represents a single bracketed symbol with the level element, but not the start or end of a serious of bracketed symbols. One way to do this would be to add a type attribute to the level element within the level-display attribute group.

**Comment by mdgood** [comment]
I am thinking of something just a little bit different. Instead of including this in the `level-display` attribute group, just add a `type` attribute with a `start-stop-single` definition directly to the `<level>` element. The `level-display` attribute group contains graphical distinctions such as parentheses, brackets, and symbol size. The proposed `type` attribute is more semantic so it seems better to have it outside of that attribute group.

This would keep the new `type` attribute from also being associated with the `<accidental>` and `<accidental-mark>` elements. To me that seems like the right thing to do.

@hhpmusic, does this sound good to you?

**Comment by mdgood** [comment]
@hhpmusic Pull request #373 addresses this issue. Could you please review it if you have a chance?
