### ISSUE TITLE
What is the intent of the different "staff-type" options?

### ISSUE THREAD

**Issue by maxrothman** [w3c/musicxml#292]
According to [the docs](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-staff-type.htm), the `staff-type` element has 5 possible values: ossia, cue, editorial, regular, and alternate. Some of the values are obvious, like "regular", "ossia", and "cue". Others are at least partially documented, like "alternate". Others, like "editorial", have no documentation at all.

What are the intended use cases and visual appearances of each of the `staff-type` values?

**Comment by mdgood** [comment]
Thank you for raising this issue. The documentation for the "alternate" type is also related to issue #205. 

Editorial staves are intended for use in scores such as critical editions. They can look similar to ossia staves but are provided by the editor rather than the composer and serve a somewhat different function.

This indeed should all be better documented than it is now.

**Comment by mdgood** [comment]
Pull request #372 addresses this issue. @maxrothman, would you be able to review this? Thanks again for raising this issue.

**Comment by maxrothman** [comment]
Thanks for coming back around to this issue, the new docs are a huge improvement!
