### ISSUE TITLE
Allow octave to include -1

### ISSUE THREAD

**Issue by mscuthbert** [w3c/musicxml#303]
I was converting a set of MIDI files to MusicXML and noticed that some of my MusicXML did not validate because the MIDI for whatever reason was including notes in the lowest octave of MIDI (octave -1; MIDI 0-11) and that these pitches could not be encoded in MusicXML.  

My guess is that 99% of these notes are invalid and a corruption of MIDI files (and in fact in my data set I'm removing them),  but it's one of the few places related to notation and not to sequencing that MusicXML cannot function as a drop-in replacement for MIDI, as good or better in every respect.

Worth altering a model and potentially crashing existing systems that rely on the spec to do data validation?

**Comment by mdgood** [comment]
According to Don Byrd's [Extremes of Conventional Music Notation site](https://homes.sice.indiana.edu/donbyrd/CMNExtremes.htm), MusicXML's C0 (MIDI 12) is the lowest pitch found in CWMN. Even so, that pitch is generally considered below the range of human hearing. 

I think MusicXML's design for excluding these pitches is an improvement over MIDI's representation for notation purposes, so I lean towards keeping this as-is. One can validate with the DTD instead of the XSD if in some cases you don't want the validator to catch this.

**Comment by mscuthbert** [comment]
Sounds good and well thought to me!

**Comment by mrmiller** [comment]
As another point of view, the lowest MIDI octaves are often used to control articulations of virtual instruments (key switches). When exporting from a DAW into notation software for orchestration, it's very useful to keep those notes in situ as indicators for articulation changes where they can be replaced with proper notation.

**Comment by mdgood** [comment]
Thank you for the suggestion @mrmiller. This type of playback change is represented differently in MusicXML. Virtual instrument changes use the `<instrument-change>` element added in version 4.0, and playback techniques use the `<play>` element added in version 3.0.

Both of these elements have room for future features. Neither has direct support for saying "this playback change should be done with this key switch", and it might be good to add that. For now you would need to use the `<other-play>` element as a workaround.

If you have a proposal for how key switch support could be added into one somewhere within the `<sound>` element and its descendants, could you please open a separate issue for that? Thanks!
