### ISSUE TITLE
Octave for Clef

### ISSUE THREAD

**Issue by AlbertHart** [w3c/musicxml#316]
I have a score with this clef data:

```
       <staves>2</staves>
        <clef number="1">
          <sign>G</sign>
          <line>2</line>
          </clef>
        <clef number="2">
          <sign>F</sign>
          <line>4</line>
          </clef>
```

How do I know from this data that the "F" clef is an octave lower that the "G" clef?

I can hardwire this knowing the G/2 is the treble clef and F/4 is the bass clef. But I presume there are other possible values for <clef> than these two.

**Comment by adrianholovaty** [comment]
Hi @AlbertHart — see [here](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#ST-MusicXML-clef-sign.htm) for the list of supported clefs in MusicXML. Also see [here](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#CT-MusicXML-clef.htm#kanchor2387) for the more general documentation on the clef element.

Generally, yes, your code will need to know what "G2" and "F4" mean, in terms of their visual look/position, effect on audio playback, etc.

(Marking as closed. You might be better off asking questions like this on our [mailing list](https://lists.w3.org/Archives/Public/public-music-notation/) instead of GitHub. We try to reserve GitHub issues for ideas and bug reports as opposed to user support questions.)
