### ISSUE TITLE
Question: specification of playing (or not playing) repeats after a jump

### ISSUE THREAD

**Issue by seffka** [w3c/musicxml#322]
If a score combines repeats and, e.g., "D.C. al coda"  jump:

  ....  ||: .... :|| ... to Coda ...  D.C. al Coda ....  Coda ... ||

How repeats must be interpreted after "D.C. al coda" jump realisation:

- they must be effectively repeated as at first time (e.g., as Sibelius does)
- repeats are not realised, if specified, the last ending is used (e.g., as MuseScore does)?

Is there a way to formally specify which strategy must be enforced (e.g., for automatic playback/score following)?

**Comment by mdgood** [comment]
@seffka This is specified using the number attribute of the ending element. We just clarified this for MusicXML 4.0 as part of issue #291. If anything is still unclear please let us know in that issue. I will close this one as a duplicate.

**Comment by seffka** [comment]
Thank you @mgood for the prompt response, now the situation with the "ending" element is clear to me.
But I have a lot of score examples with  "repeat" element alone (i.e., without ending variants).

In different scores I encountered two verbal specifications of repeats handling with a coda, i.e.:
1) "no repeat":
<img width="161" alt="Screenshot 2020-07-23 at 13 55 53" src="https://user-images.githubusercontent.com/7113235/88284496-cacd7780-cced-11ea-9e1c-bee6e2bb968f.png">

2) "with repeats"
<img width="165" alt="Screenshot 2020-07-23 at 13 56 14" src="https://user-images.githubusercontent.com/7113235/88284035-f69c2d80-ccec-11ea-88b8-82c407b4b0a8.png">

Is it possible to specify it formally, e.g., as "repeat" element property?

**Comment by mdgood** [comment]
@seffka Thank you for clarifying with the additional examples. I believe you are correct that there is not a good way to specify this with MusicXML 3.1. The `times` attribute in the `<repeat>` element only specifies the number of consecutive times to play a repeated section. It does not handle whether to play the repeat after a D.S. or D.C. jump. There is a `time-only` attribute in the `<sound>` element but that does not really have anything to connect with to specify this either.

I have reopened this issue and we will consider this for the version 4.0 milestone.

If anybody has found a solution or workaround to this, besides arbitrarily deciding one way or the other or relying on importing application defaults, please let us know.

**Comment by mdgood** [comment]
One way to support this would be to add an attribute to the `<repeat>` element. The `time-only` attribute seems unnecessarily complex for this situation, and also potentially confusing with the `times` attribute. A boolean attribute like `after-jump` that takes values of yes or no seems like it would solve this issue. @seffka, does this sound good to you? 

Does anybody have a better name for this than `after-jump`? Jump seems to be the most standard English word I can find that combines da capo and dal segno marks. It is what Behind Bars uses. If there's a more precise word in another language, or any other proposals for resolving this issue, please share that here. Thanks!

**Comment by mscuthbert** [comment]
`after-jump` sounds good to me.  But it seems to me that it should just be on the repeat element or on the jump element (Segno or Coda) itself and not on the repeat.  For one, it lets a piece with many repeats define the jump behavior one and only one time for all repeats.  Then I can imagine an editor allowing one to click on the Coda sign and define the after-jump repeat behavior regardless of what repeats are added later.  For another, it allows for the rare (but you'll see it if you play musical theater) case where you have a segno and a coda jump with different after-jump rules.

It is probably too complex to implement, but thinking even more, it should probably go on both `repeat` and the `coda`, `segno` tags, with individual `repeat` elements able to override the global after-jump state of the `D.S./Segno` sign.

**Comment by mdgood** [comment]
@mscuthbert Thanks for this feedback. Do you have an example of a coda and a segno causing different after-jump repeat behavior for the same repeat, when that repeat is not part of an ending? With music under endings, we can already control things with the `number` attribute. We should be sure to qualify that this only applies to backward repeats that are not part of an ending, the same restrictions that already apply to the `times` attribute.

I am sure I have seen codas and segnos cause different after-jump behavior in different sections of the same piece. I think this proposal handles that situation.

**Comment by seffka** [comment]
Sorry for the delay.
I agree with @mscuthbert that rather jump elements ("D.C. al Coda/D.S. al Coda" ) should be modified.
 - In scores, the behavior is specified once near "D.C. al Coda"/D.S. al Coda," no matter how many repeats it affects.
  Though I can't deny it's possible, I never saw a score with different policies for different repeats.
 - I checked some of the typesetting software: this policy is set either for D.S./D.C. (museScore) or globally (Sibelius), but not for repeat sections.

**Comment by seffka** [comment]
I have a connected question (I can't find if it's ever discussed).

What are the best practices for encoding repeats/jumps and using "sound" elements?

I. It seems some musicxml elements bear double (markup and playback) meaning:
- repeat
- ending
Although there's sound element's "forward-repeat" attribute, but its semantics is not quite clear, and it seems not used "in the wild."

II. It's an exact specification to duplicate segno and coda markup elements with sound elements (e.g., https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-segno.htm)

III. There are sound attributes for jumps ("dalsegno," "dacapo"), but there's no dedicated markup element (it's just "words" element with, e.g., "D.C. al coda" text).

Practically quite often, playback tags for repeat structure are missing, and software has to re-construct them from markup.
To improve it, I have the following suggestions:
- totally omit "sound" elements here (by moving all the functionality to markup, as with "repeat" and "ending" elements). In the latter case, introducing a new "jump" element for "D.C./D.S. al coda/fine" is needed. It should be used instead of the "words" element in "direction."
- or just opposite, make "sound" elements mandatory for jumps markup in the schema
- provide detailed documentation for jumps, as it's done for repeats (https://www.musicxml.com/tutorial/the-midi-compatible-part/repeats/)

**Comment by mdgood** [comment]
Thanks @seffka and @mscuthbert. I am now understanding the proposal and rationale for moving this attribute to the D.S. or D.C. marking much better.

The problem I still see is that this doesn't seem to fit in well with the current MusicXML design. In particular, the exact playback of repeated sections marked by endings after a D.S. / D.C. jump is already supported. You use the number attribute of the `<ending>` element to indicate which times the repeat is played. For instance, if a first ending is played after a D.C., you would have the following endings:

`<ending number="1,3">1</ending>`
`<ending number="2"/>`

If it was not played you would have:

`<ending number="1"/>`
`<ending number="2,3">2</ending>`

This is why I was looking to add an attribute to the repeat rather than to the jump. It makes the two representations more consistent. If we add the attribute to the jump, I am afraid it leads to strange interactions with the `<ending>` element.

When this playback choice is notated - often it is not - this does lead to a difference between where the notation occurs and where the markup occurs. This is not ideal. I think I still prefer it to the alternative of having two potentially conflicting attributes controlling this aspect of playback.

Because of our needs for compatibility with previous MusicXML versions, I don't think we can either omit the `<sound>` elements or make them mandatory. This would be a great area for MNX to improve based on our MusicXML experience.

I do hope we can clarify the documentation, both for jumps and for the `forward-repeat` attribute. That attribute is used to indicate an "invisible" forward repeat, such as a repeat that is implied at the start of a new section of a piece. An example is the implied forward repeat at the start of the Menuetto in the Handel Flute Sonata in G, HWV 363b.

I will see if we can improve the `forward-repeat` attribute as part of this issue. The more general documentation on jumps would likely need to wait until we are working on the specification. 

Thank you again for this enlightening discussion. Perhaps there is another design idea out there that can improve the benefits and reduce the drawbacks?

**Comment by mdgood** [comment]
Pull request #390 addresses both playing or not playing repeats after a jump, along with clarifying the forward-repeat attribute documentation. It does this in a way that is compatible with and makes minimal changes to the existing MusicXML design. 

@seffka, could you please let me know if this succeeds in clarifying both these issues? Thanks again for raising this and clarifying things when I initially misunderstood the problem.

**Comment by seffka** [comment]
Thanks @mgood, after-jump attribute solves the issue and forward-repeat documentation is clear.
