### ISSUE TITLE
Allow attaching lyrics to chords instead of to notes

### ISSUE THREAD

**Issue by samuelbradshaw** [w3c/musicxml#327]
Currently, as I understand the MusicXML spec, a lyric syllable has to be attached to a note. In choral music (SATB, for example), multiple parts might be singing the same words. To prevent the same lyrics from showing multiple times, each syllable is associated with only one of the notes in the parts that sing that syllable.

Some interactive applications provide a way to turn individual parts on and off. Because lyrics are attached to only one part, turning off that part also turns off the lyrics.

Is it possible to attach a lyric syllable to a chord instead of to a note? This would allow showing and hiding parts without affecting the lyrics.

**Comment by adrianholovaty** [comment]
> Some interactive applications provide a way to turn individual parts on and off. Because lyrics are attached to only one part, turning off that part also turns off the lyrics.

This sounds like a problem with the interactive application rather than a problem strictly with MusicXML, no? Hiding a part's notation should be possible while retaining that part's lyrics (Soundslice allows this, for example).

> Is it possible to attach a lyric syllable to a chord instead of to a note?

Just to be clear: do you mean chords as in MusicXML's `<harmony>` element (e.g., "G7"), or chords as in MusicXML's `<chord>` element (e.g., more than one note being performed at the same time)? Either way, I don't immediately see how this would solve the problem, because both `<harmony>` and `<chord>` are defined in the context of a part.

I think the "right" way to do this would be to encode lyrics redundantly — encode the same lyric syllables in each part — and add some front-end logic in your interactive application to show/hide them intelligently. For example, you might opt to hide the redundant lyrics if two parts are displayed next to each other.

**Comment by mdgood** [comment]
Hi @samuelbradshaw - you wrote a similar issue up before and I transferred it over to the [MNX issue list](https://github.com/w3c/mnx/issues/177). MusicXML doesn't have chords as an object but MNX does, so this seems better to improve there. As @adrianholovaty mentions there are also workarounds that MusicXML applications can use; I describe another one in the linked MNX issue. Thanks!

**Comment by samuelbradshaw** [comment]
You're right, it is similar – thanks for re-finding and linking that!
