### ISSUE TITLE
Support pedal lines that start without a downstroke

### ISSUE THREAD

**Issue by mscuthbert** [w3c/musicxml#335]
Related to #302 ...My student Kevin Costello also wonders if it is possible to have other representations besides "Ped" for the pedal.  Amy Beach uses "con pedale" in some places which should represent a pedal start, but without the glyph.

Could pedal type become a container for text that defaults to the SMuFL glyph for Ped if empty?

**Comment by hhpmusic** [comment]
I also ask for this, since there are several cases for this, e.g., sempre ped., where the ped is a pedal symbol, and there's no asterisk and line at all, forming a single pedal element. In Dolet for Sibelius, I only found a starting point of the pedal line, no ending, which will be imported and displayed incorrectly. The braille conversion also needs this to clarify, otherwise for example, in Musescore, we always get only a pure pedal line with both start and stop, no text and with an incorrect ending indication in braille.

**Comment by mdgood** [comment]
I apologize for the delay in responding to this.

In general this type of text + symbol + line can be handled by combining multiple `<direction-type>` elements into a single `<direction>`, using a `<sound>` element to convey the pedal playback if no `<pedal>` direction is used. For @hhpmusic we can still use a `<pedal>` element, but for @mscuthbert a `<bracket>` element would be needed.

However, I see one case where even this approach would not work. That is if the "con pedale" text is then followed by a line that includes pedal change marks. 

For that we would need something like #302, but expanded so that we could indicate the lack of an upstroke at the start of the line. This would also be more semantic than the current MusicXML 3.1 approach.

@mscuthbert, does that approach sound reasonable to you? I think that may fit in the best with the current MusicXML design but am happy to hear alternate approaches. There is a larger issue of improved semantics for different types of lines that we are deferring to MNX.

Also, if there is an example of this alternate starting pedal text combined with pedal lines with ^ pedal changes, could you please let me know?

@hhpmusic, I think that your case is more a matter of the MusicXML export software than the format itself. I know the problem in the Dolet for Sibelius plug-in is due to the limited access to font data within Sibelius plug-ins.

**Comment by mdgood** [comment]
One possibility would be to add a new "resume" type to the `<pedal>` element. This would work like the "start" type but not include the explicit downstroke at the start of the pedal marking. This handles 2 cases:

- The situation raised here, where pedal text is combined with a line that includes pedal changes.
- Repertoire similar to that mentioned in #302, where "simile" pedal line markings are resumed with a line (no downstroke) followed by additional pedal changes before concluding.

If this sounds good to folks like @mscuthbert, @hhpmusic, and @pianobench, I'd like to add this in for 4.0. Comments from others are of course welcome!

**Comment by PianoBench** [comment]
Sounds good to me, Michael.

George

**Comment by hhpmusic** [comment]
This makes sense to me too.

**Comment by mdgood** [comment]
I have renamed this issue to address the scope more precisely. This issue handles alternative text plus piano pedal lines with changes, but also discontinued and resumed piano pedal lines with changes.
