### ISSUE TITLE
Does Musicxml support such kinds of time signatures?

### ISSUE THREAD

**Issue by hhpmusic** [w3c/musicxml#341]
I found there are quite unusual time signatures in some scores, e.g., Florent Schmitt's Ombres. It's very tricky to have these time signatures engraved, and we have to use lots of alternative ways to get them in braille. These time signatures either have fractions at the upper part or have unusual beat units. Is it possible to express such things in Musicxml? Part of these signatures can be found here:
https://en.wikipedia.org/wiki/Time_signature#Irrational_meters
https://en.wikipedia.org/wiki/Time_signature#Variants

Haipeng

**Comment by mscuthbert** [comment]
The variants form was once quite common (Hindemidth) and fits in to common-music notation.  I thought we had a "symbolize denominator" somewhere that supports it (oh, no, that's just in music21).  The "irrational meters" (poorly named: they are rational, just non-power-of-two) is getting to be more common.  I think they should be supported, but I can imagine delaying that for some time.

With symbolize-denominator, the problem arises with, what symbol for 6/8 if you want 2/(dotted-quarter)?  Finale's time signature representation is well-equipped to do this (since you can use EDUs for beats), but harder in musicxml.

**Comment by mdgood** [comment]
@hhpmusic @mscuthbert Thanks for the question and discussion. Yes, MusicXML 3.1 supports all of these time signatures. There is no restriction on the content of the numerator or denominator fields so irrational meters are straightforward:

```
<time>
  <beats>2</beats>
  <beat-type>6</beat-type>
</time>
```

However, notation software support for irrational meters that play back correctly is limited. I don't know of any MusicXML software that supports irrational meters during export or import, but would be happy to hear about them.

The variants are also all covered in MusicXML. Here are two different encodings of 2½/4, plus the 3/eighth and 2/dotted quarter examples:

```
<time>
  <beats>2 1/2</beats>
  <beat-type>4</beat-type>
</time>

<time>
  <beats>2½</beats>
  <beat-type>4</beat-type>
</time>

<time symbol="note">
  <beats>3</beats>
  <beat-type>8</beat-type>
</time>

<time symbol="dotted-note">
  <beats>6</beats>
  <beat-type>8</beat-type>
</time>
```

Looking at the definition of the dotted-note value, it might be better to say "three times the beat-type duration" rather than "three times the beat-type value".

Aside from that I don't think there are any changes we need to make for MusicXML 4.0. But if you find some of the specific documentation unclear, please let us know.

**Comment by hhpmusic** [comment]
Thank you very much! I just asked this to ensure Musicxml supports them. So it's of no problem to have Musescore to include some of these strange time signatures when exporting.
