### ISSUE TITLE
Question: placement attibute inheritance in `<direction>` element

### ISSUE THREAD

**Issue by cecilios** [w3c/musicxml#356]
Both `<direction>` element and some of its `direction-type` children elements (e.g. `<dynamics>`) have a `placement` attribute. I have some doubts about the expected behaviour:

- Is `placement` in `<direction>` always inherited by its children (e.g. `<dynamics>` element)?
- If this is the case, what is the official behavior when `placement` is defined in both but they are different? e.g.
```
<direction placement="above">
    <direction-type>
        <dynamics placement="below"><ff/></dynamics>
    </direction-type>
    <staff>1</staff>
</direction>
```

I would appreciate a clarification.

Thank you in advance,
Cecilio

**Comment by mdgood** [comment]
@cecilios Thanks for raising this. Does this occur anywhere else besides the `<dynamics>` element? The placement attribute is present in this element because it can be used as a child of the `<notations>` element as well as a `<direction-type>` element.

In general, the lower-level elements override what is in the higher-level elements. That works for attributes like print-object but not so much for this situation.

My inclination would be to say that the placement attribute should be ignored when the `<dynamics>` element is a child of the `<direction-type>` element. Does that make sense to you?

**Comment by mdgood** [comment]
I see now that this duplicates #43, so I will add that to the 4.0 milestone and close this issue.

**Comment by cecilios** [comment]
Thank you. I wasn't aware of #43. For me, any solution is valid, and the important point is to clarify the expected behavior. My MusicXML importer currently does the opposite, `<dynamics>` placement overrides the placement in `<direction-type>` element. But the other behavior also makes sense.

I didn't find a real example file with this conflict on it and the issue originated when having to decide what to do in my software.

Thank you!
