### ISSUE TITLE
Clarification on invisible notes 

### ISSUE THREAD

**Issue by cecilios** [w3c/musicxml#358]
I would appreciate some clarifications about invisible notes `<note print-object="no" print-spacing="no">` in MusicXML files.  What are they for? Should they played in playback?

In sample `ActorPreludeSample` (from https://www.musicxml.com/music-in-musicxml/example-set/) in part P16, measure 33, there are many invisible short notes `<note print-object="no" print-spacing="no">` that seems to be associated to a visible one (half note) having a tremolo. I do not understand this construction. Is it a trick for implementing the tremolo for playback? 

Could I safely ignore invisible notes in a MusicXML importer when ornaments are properly managed by the software in playbacK?

Thanks in advance for any help to understand this.

**Comment by mdgood** [comment]
Hi @cecilios - I think you are understanding this correctly. Yes, in that example the invisible notes are used for implementing tremolo playback. 

More generally, invisible notes are used for playback rather than visual appearance. Something similar happens with notes that are included within music following a `<slash type="start">` element. In the other direction, the `<cue/>` element is used for notes that appear but do not play.

Invisible notes can be used for other types of playback / appearance distinctions. It is up to the application to determine when invisible notes might be ignored if playback differences can be handled a different way.

Is there a documentation request that you think could help clarify this? If not I will close this issue.

**Comment by cecilios** [comment]
Thanks a lot and Happy New Year! The documentation for `%print-object` and `%print-spacing` in `common.mod` suggest this interpretation but I was not sure if I understood it correctly, and if this was the intended use and there were no other use cases that I would have missed.

Thank you for your detailed explanation. I'm closing this.
