### ISSUE TITLE
Allow transposition double direction='above'

### ISSUE THREAD

**Issue by mscuthbert** [w3c/musicxml#368]
Just as cellos and basses are often doubled in orchestral literature, commonly in band literature, flutes and piccolos are written on the same staff with piccolos sounding an octave higher.  An attribute in the double tag would help this.  Either:

`<double direction="above"/>`  (default = below)

or 

`<double above="yes"/>`  (default = no)

**Comment by mdgood** [comment]
Examples include the first published versions of the full scores of the Holst Suites Op. 28 from the 1920s.

I am leaning towards using the above attribute but could be easily persuaded otherwise. If anyone has strong feelings either way, or another suggestion for implementing this, please let us know.
