### ISSUE TITLE
Specify smufl glyph for wavy-line element

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#397]
SMuFL includes a large number of wavy line glyphs in the [Multi-segment lines](https://w3c.github.io/smufl/latest/tables/multi-segment-lines.html) range. MusicXML however cannot distinguish between these different type of wavy lines.

This could be done by adding a `smufl` attribute to the `<wavy-line>` element. The glyphs allowed in this attribute could be restricted to the wiggle and guitar vibrato stroke glyphs in the range, exclude the beam glyphs.

This allows for repetition of a single glyph in the wavy line. The glyph can change within a line by specifying a different `smufl` attribute value as part of a `<wavy-line type="continue"/>` element. 

If we decide we want to support a repeated pattern of glyphs in the future, this could be done by adding some child elements to represent the pattern. Solving for the simpler problem now should not cause problems for solving for the more complex problem in a later version.

**Comment by jsawruk** [comment]
Some thoughts:
- I would recommend using the semantic name (wiggleTrillFastest) rather than the Unicode codepoint (U+EAA0) or literal Unicode character.
- I think calling this attribute `smufl` might create a tight coupling between MusicXML and SMuFL. I propose using `glyph` as the attribute name instead. I don't feel strongly about this.

Example:
```
<wavy-line glyph="wiggleTrillFastest" />
```

Perhaps you could also change the glyph when `type=continue` to create complex wavy lines, such as the example in SMuFL:
```
wiggleVibratoStart + wiggleVibratoSmallestFastest + wiggleVibratoMediumSlower 
+ wiggleVibratoMediumSlowest + wiggleVibratoMediumFaster + wiggleVibratoMediumFasterStill
```
might be represented as:
```
<!-- start a new wavy line -->
<wavy-line glyph="wiggleVibratoStart" />
 
<!-- continue the current wavy line, but change the glyph -->
<wavy-line type="continue" glyph="wiggleVibratoSmallestFastest" />
...
```

**Comment by mdgood** [comment]
Thanks @jsawruk! We already added `smufl` attributes to many elements in MusicXML 3.1. This is extending an existing MusicXML concept to a new element. As you suggest, these attributes all use canonical glyph names, not code points.
