### ISSUE TITLE
Provide a way to define a "triplet feel" for measure(s).

### ISSUE THREAD

**Issue by GeorgeTailor** [w3c/musicxml#405]
Currently, MusicXML does not define any way of providing information how to play with triplet feel.

It should be possible to somehow annotate a note both visually and in terms of duration how to play such notes.
The most common triplet feel is when two eighth notes are played as a triplet of a quarter note and an eighth note (or three eighth notes, second being tied to the first one).

To my knowledge there are the following triplet feel types:
- triplet 8th (triplet of 4th + 8th)
- triplet 16th (triplet of 8th + 16th)
- dotted 8th (dotted 8th + 16th)
- dotted 16th (dotted 16th + 32nd)
- scottish 8th (16th + dotted eighth)
- scorrish 16th (32nd + dotted 16th)

While duration can be expressed with `measure.attributes.divisions` + `measure.notes[n].duration` to get the desired duration of a note, the standard currently lacks a definition how to name and visualize it, some kind of a marker above the measure to tell the performer such info.

Validation passes, since duration of `triplet 8th` = duration of two 8th notes and that's how it should be visualized (as two separate 8th notes).

**Comment by mdgood** [comment]
Hi @GeorgeTailor - MusicXML 4.0 added a `<swing>` element that allows you to specify this type of playback, and the `<metronome>` element has long let you set up visual tempo relationships like this. You can see an example of using both these elements at:

https://w3c.github.io/musicxml/musicxml-reference/examples/metronome-note-element/

We do need to fix the documentation for the `<swing>` element. This is one of the elements effected by a known bug in the documentation generator tool. That should be fixed by the end of this week.

If there are any further questions or if I am misunderstanding the issue, please let us know.

**Comment by GeorgeTailor** [comment]
Hmm, I was looking at the wrong doc then.
I checked with version 3.0. [The main page ](https://www.musicxml.com/for-developers/) leads to version 3.0 [here](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm) which does not have what I described in this issue.
Maybe we could update the main page to point to the newest spec?

**Comment by mdgood** [comment]
Yes, we will be doing that on the musicxml.com site once Version 4.0 is officially released, which is currently planned for June 1. You are far from the first person who has been misled by the out-of-date 3.0 documentation.
