### ISSUE TITLE
google search for MusicXML element fails

### ISSUE THREAD

**Issue by jsutdolph** [w3c/musicxml#421]
search for eg "metronome" auto redirects from specific <metronome> page to generic MusicXML title page

**Comment by adrianholovaty** [comment]
I believe this is because the old usermanuals.musicxml.com pages do a blanket redirect to https://www.w3.org/2021/06/musicxml40/. It'd be nice to add specific redirects for each individual page, but that'd take extra work.

In the meantime, I'd suggest making sure to click the w3c.github.io results in Google searches for MusicXML elements. Eventually this will work itself out as Google updates its index and accounts for those redirects.

**Comment by mdgood** [comment]
I believe @adrianholovaty's analysis is correct. We did put in page-specific redirects for the tutorial that used to be on the musicxml.com site. But the manual is huge, even for 3.0. It would have taken a lot of extra work for me to even figure out the redirects, much less have our IT team implement them. As Adrian mentions this will work itself out over time.

**Comment by mdgood** [comment]
I will close this now as a Google search for "musicxml metronome" is now going to the MusicXML 4.0 documentation - in my test case, to the [`<metronome>` example](https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/metronome-element/).
