### ISSUE TITLE
Errors in examples

### ISSUE THREAD

**Issue by infojunkie** [w3c/musicxml#496]
At https://github.com/infojunkie/musicxml-midi/pull/40, I am working on extracting the MusicXML examples to use them as test cases. 

Part of my script validates each example using `xmllint` and the 4.0 spec. I found that 5 examples are not validating:
- accordion-middle-element: `Element 'accordion-middle': '' is not a valid value of the atomic type 'accordion-middle'.`
- circular-arrow-element: `Element 'circular-arrow': [facet 'enumeration'] The value 'anti-clockwise' is not an element of the set {'clockwise', 'anticlockwise'}.`
- interchangeable-element: `Element 'time-relation': This element is not expected. Expected is ( beats ).`
- inversion-element: `Element 'inversion': This element is not expected. Expected is ( kind ).`
- voice-element: `Element 'tuplet', attribute 'bracket': [facet 'enumeration'] The value 'none' is not an element of the set {'yes', 'no'}.`

I'll be submitting a PR to fix these errors.

**Comment by mscuthbert** [comment]
Thanks -- these look right to me -- I'm going to set up a 4.1 branch and then merge.

**Comment by rettinghaus** [comment]
Fixes for examples should also backported to 4.0.

**Comment by mscuthbert** [comment]
> Fixes for examples should also backported to 4.0.

Hi Klaus Re: backporting: I'm much against for anything before the current spec (so no backports to 3.2 etc.) -- for the current spec, I think there are good reasons to keep it stable (unchanged after published) and also to make it correct (=backporting).  

Because it's a larger philosophical decision, I will leave the decision on this to the next MusicXML chair -- to be chosen in early 2026.  Happy New Year!
