### ISSUE TITLE
 JAXB Parsing Fails

### ISSUE THREAD

**Issue by Yokojona** [w3c/musicxml#566]
#### Problem 1: Inaccessible External URLs
The `musicxml.xsd` schema references external XSD files via URLs:  
```xml
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.musicxml.org/xsd/xml.xsd"/>
<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.musicxml.org/xsd/xlink.xsd"/>
```

These URLs are inaccessible, causing errors when parsing with JAXB's `xjc` tool:  
```
Failed to read schema document 'http://www.musicxml.org/xsd/xml.xsd'.
Failed to read schema document 'http://www.musicxml.org/xsd/xlink.xsd'.
```

#### Fix:
Replaced URLs with local files:  
```xml
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="xlink.xsd"/>
```

#### Problem 2: Naming Conflicts
After resolving the URL issue, `xjc` failed due to naming conflicts for `link`, `segno`, `coda`, and `bookmark`, which were defined multiple times in different contexts.  
```
[ERROR] Element "link" shows up in more than one properties.
[ERROR] Property "Segno" is already defined.
[ERROR] Property "Coda" is already defined.
```

#### Fix:
Renamed conflicting elements based on their context:
- `link` → `credit-link` (in `credit`) and `music-data-link` (in `music-data`).
- `segno` → `barline-segno` (in `barline`) and `direction-type-segno` (in `direction-type`).
- `coda` → `barline-coda` (in `barline`) and `direction-type-coda` (in `direction-type`).
- `bookmark` → `credit-bookmark` (in `credit`) and `music-data-bookmark` (in `music-data`).

#### Result:
After these changes, the `xjc` tool successfully parsed the schema and generated unique Java classes without errors, improving compatibility with JAXB and similar tools.

**Comment by infojunkie** [comment]
Regarding the 404 xsd, there's been plenty of discussion about that https://github.com/w3c/musicxml/discussions/445 and elsewhere.

I was curious about the reported naming conflicts, so I ran `curl -O https://www.w3.org/2012/04/XMLSchema.xsd && xmllint --noout --schema XMLSchema.xsd musicxml.xsd` to validate the MusicXML schema file. I received no error. 

I ran `xjc -d java musicxml.xsd` to see the errors for myself and got the following:
```
parsing a schema...
[ERROR] Element "link" shows up in more than one properties.
  line 5848 of file:/home/kratib/src/infojunkie/musicxml-midi/src/xsd/musicxml.xsd

[ERROR] The following location is relevant to the above error
  line 5839 of file:/home/kratib/src/infojunkie/musicxml-midi/src/xsd/musicxml.xsd

[ERROR] Property "Segno" is already defined. Use &lt;jaxb:property> to resolve this conflict.
  line 3235 of file:/home/kratib/src/infojunkie/musicxml-midi/src/xsd/musicxml.xsd

[ERROR] The following location is relevant to the above error
  line 3242 of file:/home/kratib/src/infojunkie/musicxml-midi/src/xsd/musicxml.xsd

[ERROR] Property "Coda" is already defined. Use &lt;jaxb:property> to resolve this conflict.
  line 3236 of file:/home/kratib/src/infojunkie/musicxml-midi/src/xsd/musicxml.xsd

[ERROR] The following location is relevant to the above error
  line 3243 of file:/home/kratib/src/infojunkie/musicxml-midi/src/xsd/musicxml.xsd

Failed to parse a schema.
```

Since the MusicXML schema is validating against the XSD schema, I see no reason to change the MusicXML schema itself (not to mention version incompatibility with hundreds of softwares and hundreds of thousands of MusicXML files). It would seem that `jaxb` needs some tweaking to work properly - I suggest looking at `<jaxb:property>` as a starting point.

**Comment by Yokojona** [comment]
[https://w3c.github.io/musicxml/tutorial/code-generation/](url)

here is the official solution.
