### ISSUE TITLE
Allow representation of measure number display text

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#69]
MusicXML has always tried to support the differences between how music looks and how music sounds, with extensive suggestions for specific visual appearance and playback. One area where this coverage is missing is in measure numbers.

Currently measure numbers are represented in the number attribute of the measure element. The value there serves more as an internal identifier to align measures between parts than as a visual display. Formatting is controlled by the implicit attribute, which indicates that a particular measure number should not be displayed, and by the separate measure-numbering element.

This creates problems in many situations, such as when multiple movements are combined into a single piece and measure numbering resets at the beginning of each one.

Measure numbers should have similar capabilities for display text as other MusicXML symbols where display may not match other aspects of internal representation, such as the harmony element provides for chord symbols.

See the MusicXML forum discussion started by Niv Haim at http://forums.makemusic.com/viewtopic.php?f=12&t=2293.

**Comment by joeberkovitz** [comment]
I think that this is an area where we risk a narrow solution to just one of the various text formatting/positioning problems in MusicXML today. Suggest we defer until we have a chance to look at the larger landscape of MusicXML text features, and how we propose to separate visual information from semantic.

**Comment by mdgood** [comment]
Perhaps we could split this into two issues, one for display text and one for formatting? The number attribute cannot be reused within a part, as all measures with the same number attribute are grouped together when converting to timewise format. So there's no way in MusicXML 3.0 to accurately represent measure numbering for multi-section works where measure numbers start over at 1 within a single MusicXML file. 

The display text issue could be addressed by adding a text attribute to the measure element, similar to the way the text attribute is used elsewhere in MusicXML, as in chord symbols. I can see the desire to not add any more formatting attributes until we address formatting at a structural level.

**Comment by joeberkovitz** [comment]
After reading your clarification of the issue with use of `measure.@number` when parts are renumbered across sections, this actually reinforces my sense that it would be premature to solve this problem with `@text`, and that there is some significant coupling to a structural issue, namely the representation of movements (or, more generally, sections of a work).

Semantically, I don't think of measure numbers as opaque tokens. They form a sequence. While an  unconstrained textual measure label might be useful (would love to see some use cases!), the need for movement- or section-scoped numbering doesn't mean that we have to give up on the idea of measure numbers as a monotonically increasing sequence within some document scope. Clearly `@number` with its current `xs:token` type falls short of that idea (since tokens are not necessarily numbers), but `@text` is even worse in this regard. If we are solving the problems of `@number` with its non-numeric nature and its requirement of uniqueness, I'd like us to consider other directions.

In particular, applications should be able to discover that a sequence of consecutively numbered measures _is_ in fact a sequence, rather than a bunch of arbitrary textual labels that happen to mimic a sequence. Consider what happens when someone adds a new measure in a notation editor within such a sequence -- the sequential numbering should be preserved, I'd expect. To support this, instead of `@text` we could perhaps employ a new integer-typed attribute for numbering, that's scoped within a section container to remove any ambiguity from the restarts in measure numbering. 

Come to think of it, movements or sections themselves are likely to carry numbers. So we might want to make the treatment of measure and section numbers congruent in the spec.

None of this is to push for a particular solution. I'm just trying to highlight the fact that this issue has some significant coupling to other, deeper questions about document organization.

**Comment by mdgood** [comment]
@joeberkovitz, I agree that it would be desirable to have a more general, semantically stronger solution to the issue of multi-movement measure numbering. That seems best approached in MNX though. 

With MusicXML 3.1 we are filling in many of the "you can't do that" gaps in MusicXML 3.0. This is one of the last remaining significant gaps that is not in scope for 3.1. 

I would like to bring the more limited text portion of this issue into scope so we can accurately transfer multi-movement (or multi-variation) measure numbers from one application to another, without waiting for MNX.

**Comment by mdgood** [comment]
This initial description is incorrect. The `<measure-numbering>` element provides per-part formatting information for measure numbers. So it is just the display text that needs to be added. Adding the text attribute solves a practical problem with what I believe to be minimal impact for MNX.

Some of the complexity around this issue is due to the `<measure>` element doing double duty in partwise and timewise formats. MNX proposes to remove the little-used timewise format, which will help this situation.

**Comment by joeberkovitz** [comment]
Sounds good, let's do this.

**Comment by mdgood** [comment]
I have updated the title and description to remove the incorrect part about formatting. It is just the display text that is missing.

**Comment by mdgood** [comment]
We can do this by adding a text attribute to the measure element, which is a string that is at least 1 character long. If present, this is what is displayed in the measure number. The implicit attribute and measure-numbering element still control whether or not a measure number is displayed.

**Comment by mdgood** [comment]
Pull request #198 addresses this issue.

**Comment by mdgood** [comment]
Issue #213 and pull request #214 fixed a problem with the initial pull request.
