### ISSUE TITLE
Add complete SMuFL handbells range

### ISSUE THREAD

**Issue by mdgood** [w3c/musicxml#79]
MusicXML could complete its support for the SMuFL handbells range U+E810–U+E82F for better interoperability between applications. The range is documented at http://w3c.github.io/smufl/gitbook/tables/handbells.html.

MusicXML 3.0 supports most of these symbols with the handbell element, but does not include the following SMuFL 1.19 symbols:
- Mallet, bell suspended (U+E814)
- Swing up (U+E818)
- Swing down (U+E819)
- Echo 2 (U+E81C)
- Belltree (U+E81F)
- Table single handbell (U+E820)
- Table pair of handbells (U+E821)

This issue arose while analyzing MusicXML 3.0 for SMuFL support in preparation for the 2015 MusicXML community meeting at Musikmesse.

**Comment by mdgood** [comment]
This could be implemented by adding "mallet suspended", "swing up", "swing down", "echo 2", "belltree", "table single" and "table pair" enumeration values to the handbell-value simple type. The direction.mod and to30.xsl files would be updated accordingly.

**Comment by mdgood** [comment]
This issue brings up a more general point that deserves some discussion. Of all the symbols included here, only belltree represents a new symbol with a shape that isn't elsewhere used in MusicXML. Most of the others can be represented with the arrow element, while the Mallet, bell suspended can be represented with the stopped element.

SMuFL and MusicXML have different design philosophies here. SMuFL gives different glyph values to symbols that in general may look alike but have different semantics. This allows more semantic encoding and greater typographic flexibility. MusicXML in general does not do this - for example, the various semantic uses of the + symbol are all represented with the stopped element.

What should we do for MusicXML 3.1? We have the freedom to specify special SMuFL glyphs using various other- elements - for this issue it would be other-technical. Do we want to expand enumerations to cover these duplicated glyphs in MusicXML 3.1, or wait for MNX to take that different kind of approach?

This same question will come up in other issues targeted for MusicXML 3.1, such as #100.

Whichever way we decide, I think at least we want to add the belltree enumeration value to the handbell-value simple type as proposed earlier.

**Comment by JDLH** [comment]
> This issue brings up a more general point…. SMuFL gives different glyph values to symbols that in general may look alike but have different semantics. This allows more semantic encoding and greater typographic flexibility. MusicXML in general does not do this - for example, the various semantic uses of the + symbol are all represented with the stopped element.

One of my baseline desires for MNX is to have all the semantics of the score accessible to software parsing the MNX content, without any need to interpret the score visually, and without any need to compare the relative positions of marks on a drawing surface, to get semantic information. 

I think what you are saying is that SMuFL encodes the same visual appearance at multiple code points so that the code point can represent semantic differences, while MusicXML 3.1 uses the same appearance and element structure to represent semantically different notation.  If that understanding is correct, then I think SMuFL has a leg up on MusicXML 3.1. (But you mention "other-technical", and I think I don't follow your meaning there. Maybe I'm missing something.)

But, I think MusicXML 3.1 has limited scope, and my goal of semantics accessible to software may be out of scope in same respects.  In that case, I'd abstain on the question of what to do in 3.1. I just want to be sure we remember semantics accessible to software for MNX.

**Comment by mdgood** [comment]
The other-technical reference was in regard to issue #107. This now allows the different MusicXML extension elements to specify a unique SMuFL glyph name for better exchange of symbols that are in SMuFL 1.2 but not MusicXML 3.1. So that could be a fallback in the MusicXML 3.1 time frame.

I think most of us want to get to a better semantic representation, and I agree that SMuFL has an advantage here regarding visually similar symbols with different semantics. But does it make sense to at least partially change MusicXML's overall design regarding these visually identical elements in 3.1, or save that for MNX?

**Comment by mdgood** [comment]
Based on further discussions, the current proposal for this issue is:

- Add a new belltree enumeration value to the handbell-value simple type.
- Add the smufl attribute group to the arrow complex type.
- Create a new empty-placement-smufl complex type that adds the smufl attribute group to the existing empty-placement type.
- Change the type of the stopped element from empty-placement to empty-placement-smufl.

**Comment by mdgood** [comment]
Pull request #190 addresses this issue.

**Comment by mdgood** [comment]
Pull request #207 fixes a bug from the previous pull request.
